import { db } from "@workspace/db";
import { starsTable, lightCurvePointsTable } from "@workspace/db";
import type { InsertStar } from "@workspace/db";

const STARS: InsertStar[] = [
  {
    name: "Betelgeuse",
    commonName: "Alpha Orionis",
    spectralClass: "M",
    subtype: "Red supergiant",
    temperature: 3500,
    massSolar: 16.5,
    radiusSolar: 764,
    luminositySolar: 100000,
    distanceLightYears: 700,
    isAlive: true,
    transmissionAgeYears: 700,
    deathYear: null,
    constellation: "Orion",
    nasaId: "betelgeuse",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Betelgeuse_star_%28Hubble%29.jpg/800px-Betelgeuse_star_%28Hubble%29.jpg",
    generatedImageUrl: null,
    description: "Betelgeuse is a red supergiant nearing the end of its life. Expected to go supernova within the next 100,000 years — possibly imminently on cosmic timescales. The light you see left this star before Columbus crossed the Atlantic.",
    sonificationParams: { baseFrequency: 174, timbre: "fm", pulseRate: 4.2, harmonics: [1, 1.5, 2] },
  },
  {
    name: "Rigel",
    commonName: "Beta Orionis",
    spectralClass: "B",
    subtype: "Blue supergiant",
    temperature: 12100,
    massSolar: 21,
    radiusSolar: 79,
    luminositySolar: 120000,
    distanceLightYears: 860,
    isAlive: true,
    transmissionAgeYears: 860,
    deathYear: null,
    constellation: "Orion",
    nasaId: "rigel",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Rigel is a blue supergiant — one of the most luminous stars visible to the naked eye. This signal left Rigel when the Black Death was sweeping across Europe. It burns 120,000 times brighter than our Sun.",
    sonificationParams: { baseFrequency: 660, timbre: "sawtooth", pulseRate: null, harmonics: [1, 2, 3, 4, 5] },
  },
  {
    name: "Sirius",
    commonName: "Alpha Canis Majoris",
    spectralClass: "A",
    subtype: "Main sequence",
    temperature: 9940,
    massSolar: 2.1,
    radiusSolar: 1.71,
    luminositySolar: 25.4,
    distanceLightYears: 8.6,
    isAlive: true,
    transmissionAgeYears: 8.6,
    deathYear: null,
    constellation: "Canis Major",
    nasaId: "sirius",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Sirius is the brightest star in the night sky, just 8.6 light-years away. Its signal is nearly fresh — the light you see left just over 8 years ago. The ancient Egyptians tracked Sirius to predict the Nile's annual flood.",
    sonificationParams: { baseFrequency: 528, timbre: "sine", pulseRate: null, harmonics: [1, 2, 3] },
  },
  {
    name: "Proxima Centauri",
    commonName: null,
    spectralClass: "M",
    subtype: "Red dwarf",
    temperature: 3042,
    massSolar: 0.12,
    radiusSolar: 0.15,
    luminositySolar: 0.0017,
    distanceLightYears: 4.24,
    isAlive: true,
    transmissionAgeYears: 4.24,
    deathYear: null,
    constellation: "Centaurus",
    nasaId: "proxima_centauri",
    imageUrl: null,
    generatedImageUrl: null,
    description: "The nearest star to our Sun. A tiny, dim red dwarf that will outlive our Sun by trillions of years. So faint it was not discovered until 1915. This signal is the freshest in our catalog — just 4.24 years old.",
    sonificationParams: { baseFrequency: 120, timbre: "fm", pulseRate: 8.1, harmonics: [1, 1.5, 2] },
  },
  {
    name: "Vega",
    commonName: "Alpha Lyrae",
    spectralClass: "A",
    subtype: "Main sequence",
    temperature: 9602,
    massSolar: 2.14,
    radiusSolar: 2.36,
    luminositySolar: 40.1,
    distanceLightYears: 25.0,
    isAlive: true,
    transmissionAgeYears: 25,
    deathYear: null,
    constellation: "Lyra",
    nasaId: "vega",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Vega was the pole star 14,000 years ago and will be again in 13,727 years. A benchmark star used to calibrate the entire photometric scale of astronomy. The contact novel imagined it as the source of an alien signal.",
    sonificationParams: { baseFrequency: 528, timbre: "sine", pulseRate: null, harmonics: [1, 2, 3] },
  },
  {
    name: "Arcturus",
    commonName: "Alpha Boötis",
    spectralClass: "K",
    subtype: "Red giant",
    temperature: 4286,
    massSolar: 1.08,
    radiusSolar: 25.4,
    luminositySolar: 170,
    distanceLightYears: 36.7,
    isAlive: true,
    transmissionAgeYears: 36.7,
    deathYear: null,
    constellation: "Boötes",
    nasaId: "arcturus",
    imageUrl: null,
    generatedImageUrl: null,
    description: "The brightest star in the northern sky. Its light was used to open the 1933 World's Fair in Chicago — the signal arriving from a star 37 light-years away, switched on a photoelectric cell, illuminating the exposition.",
    sonificationParams: { baseFrequency: 261, timbre: "triangle", pulseRate: null, harmonics: [1, 2, 3] },
  },
  {
    name: "Antares",
    commonName: "Alpha Scorpii",
    spectralClass: "M",
    subtype: "Red supergiant",
    temperature: 3570,
    massSolar: 12,
    radiusSolar: 700,
    luminositySolar: 75000,
    distanceLightYears: 550,
    isAlive: true,
    transmissionAgeYears: 550,
    deathYear: null,
    constellation: "Scorpius",
    nasaId: "antares",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Antares — rival of Mars, named for its reddish hue. A red supergiant so vast that if placed at our Sun, it would engulf Mars. The light arriving now left during the Ottoman conquest of Constantinople.",
    sonificationParams: { baseFrequency: 174, timbre: "fm", pulseRate: 5.7, harmonics: [1, 1.5, 2] },
  },
  {
    name: "Polaris",
    commonName: "North Star",
    spectralClass: "F",
    subtype: "Yellow supergiant (Cepheid)",
    temperature: 6015,
    massSolar: 5.4,
    radiusSolar: 46,
    luminositySolar: 2500,
    distanceLightYears: 433,
    isAlive: true,
    transmissionAgeYears: 433,
    deathYear: null,
    constellation: "Ursa Minor",
    nasaId: "polaris",
    imageUrl: null,
    generatedImageUrl: null,
    description: "The star that has guided navigators for millennia. A Cepheid variable — it pulses, expanding and contracting. The light arriving now departed when Galileo Galilei was alive, still decades before Newton would be born.",
    sonificationParams: { baseFrequency: 440, timbre: "sine", pulseRate: 12.6, harmonics: [1, 2, 3] },
  },
  {
    name: "Deneb",
    commonName: "Alpha Cygni",
    spectralClass: "A",
    subtype: "Blue-white supergiant",
    temperature: 8525,
    massSolar: 19,
    radiusSolar: 203,
    luminositySolar: 196000,
    distanceLightYears: 2600,
    isAlive: true,
    transmissionAgeYears: 2600,
    deathYear: null,
    constellation: "Cygnus",
    nasaId: "deneb",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Deneb is the most distant star routinely visible to the naked eye. Intrinsically one of the most luminous stars in the galaxy. The signal arriving now left during the Bronze Age — before Rome, before Buddha, before the first Olympic games.",
    sonificationParams: { baseFrequency: 528, timbre: "sine", pulseRate: null, harmonics: [1, 2, 3, 4] },
  },
  {
    name: "Eta Carinae",
    commonName: null,
    spectralClass: "O",
    subtype: "Luminous Blue Variable",
    temperature: 40000,
    massSolar: 100,
    radiusSolar: 240,
    luminositySolar: 5000000,
    distanceLightYears: 7500,
    isAlive: true,
    transmissionAgeYears: 7500,
    deathYear: null,
    constellation: "Carina",
    nasaId: "eta_carinae",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Eta_Carinae.jpg/800px-Eta_Carinae.jpg",
    generatedImageUrl: null,
    description: "Eta Carinae is one of the most massive and luminous stars known — potentially over 100 solar masses. It is expected to explode as a hypernova. Its 1843 eruption briefly made it the second brightest star in the sky. The light arriving now left before the first cities of Mesopotamia.",
    sonificationParams: { baseFrequency: 880, timbre: "sawtooth", pulseRate: 22.3, harmonics: [1, 2, 3, 4, 5] },
  },
  {
    name: "UY Scuti",
    commonName: null,
    spectralClass: "M",
    subtype: "Red hypergiant",
    temperature: 3365,
    massSolar: 7,
    radiusSolar: 1708,
    luminositySolar: 340000,
    distanceLightYears: 9500,
    isAlive: true,
    transmissionAgeYears: 9500,
    deathYear: null,
    constellation: "Scutum",
    nasaId: "uy_scuti",
    imageUrl: null,
    generatedImageUrl: null,
    description: "UY Scuti may be the largest known star by radius. If placed at our Sun, it would engulf Jupiter's orbit. The signal arriving now left when mammoths still walked the Earth. A single heartbeat of this star takes years.",
    sonificationParams: { baseFrequency: 87, timbre: "fm", pulseRate: 2.8, harmonics: [1, 1.5, 2] },
  },
  {
    name: "Aldebaran",
    commonName: "Alpha Tauri",
    spectralClass: "K",
    subtype: "Red giant",
    temperature: 3910,
    massSolar: 1.16,
    radiusSolar: 44.2,
    luminositySolar: 518,
    distanceLightYears: 65,
    isAlive: true,
    transmissionAgeYears: 65,
    deathYear: null,
    constellation: "Taurus",
    nasaId: "aldebaran",
    imageUrl: null,
    generatedImageUrl: null,
    description: "The red eye of Taurus the Bull. The Pioneer 10 spacecraft, launched in 1972, is traveling toward Aldebaran and will arrive in approximately 2 million years. The light you see left this star in 1959.",
    sonificationParams: { baseFrequency: 261, timbre: "triangle", pulseRate: null, harmonics: [1, 2, 3] },
  },
  {
    name: "Spica",
    commonName: "Alpha Virginis",
    spectralClass: "B",
    subtype: "Binary, blue giant",
    temperature: 25300,
    massSolar: 10.25,
    radiusSolar: 7.4,
    luminositySolar: 12100,
    distanceLightYears: 250,
    isAlive: true,
    transmissionAgeYears: 250,
    deathYear: null,
    constellation: "Virgo",
    nasaId: "spica",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Spica is a binary system — two hot stars orbiting so close they are egg-shaped by mutual gravity. This signal left when the American Revolution was still decades away. Hipparchus used Spica to discover the precession of the equinoxes in 127 BCE.",
    sonificationParams: { baseFrequency: 660, timbre: "sawtooth", pulseRate: null, harmonics: [1, 2, 3, 4] },
  },
  {
    name: "Mira",
    commonName: "Omicron Ceti",
    spectralClass: "M",
    subtype: "Pulsating red giant",
    temperature: 3150,
    massSolar: 1.18,
    radiusSolar: 350,
    luminositySolar: 9000,
    distanceLightYears: 420,
    isAlive: true,
    transmissionAgeYears: 420,
    deathYear: null,
    constellation: "Cetus",
    nasaId: "mira",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Mira — 'the wonderful' — is a long-period variable star that brightens and dims over a 332-day cycle, sometimes visible to the naked eye and sometimes not. It leaves a comet-like tail of gas 13 light-years long as it moves through space.",
    sonificationParams: { baseFrequency: 174, timbre: "fm", pulseRate: 4.5, harmonics: [1, 1.5, 2] },
  },
  {
    name: "Fomalhaut",
    commonName: "Alpha Piscis Austrini",
    spectralClass: "A",
    subtype: "Main sequence",
    temperature: 8590,
    massSolar: 1.92,
    radiusSolar: 1.84,
    luminositySolar: 16.6,
    distanceLightYears: 25,
    isAlive: true,
    transmissionAgeYears: 25,
    deathYear: null,
    constellation: "Piscis Austrinus",
    nasaId: "fomalhaut",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Fomalhaut is one of only a handful of stars where a planet has been directly imaged in visible light. A bright debris disk surrounds it — the signature of an active planetary system. This signal left in the year 2001.",
    sonificationParams: { baseFrequency: 528, timbre: "sine", pulseRate: null, harmonics: [1, 2, 3] },
  },
  {
    name: "Delta Cephei",
    commonName: null,
    spectralClass: "F",
    subtype: "Cepheid variable",
    temperature: 5900,
    massSolar: 4.5,
    radiusSolar: 32,
    luminositySolar: 1350,
    distanceLightYears: 887,
    isAlive: true,
    transmissionAgeYears: 887,
    deathYear: null,
    constellation: "Cepheus",
    nasaId: "delta_cephei",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Delta Cephei is the prototype of a class of variable stars that became the first 'standard candles' for measuring cosmic distances. Its 5.37-day pulsation period made it possible to measure distances to other galaxies. The signal arrived having traveled since the Middle Ages.",
    sonificationParams: { baseFrequency: 440, timbre: "sine", pulseRate: 10.7, harmonics: [1, 2, 3] },
  },
  {
    name: "Epsilon Eridani",
    commonName: null,
    spectralClass: "K",
    subtype: "Main sequence",
    temperature: 5084,
    massSolar: 0.82,
    radiusSolar: 0.74,
    luminositySolar: 0.34,
    distanceLightYears: 10.5,
    isAlive: true,
    transmissionAgeYears: 10.5,
    deathYear: null,
    constellation: "Eridanus",
    nasaId: "epsilon_eridani",
    imageUrl: null,
    generatedImageUrl: null,
    description: "One of the first stars targeted by SETI. Epsilon Eridani hosts a confirmed planet and a circumstellar disk. Project Ozma listened to this star in 1960 for extraterrestrial signals. The light you see left in 2015.",
    sonificationParams: { baseFrequency: 261, timbre: "triangle", pulseRate: null, harmonics: [1, 2, 3] },
  },
  {
    name: "Canopus",
    commonName: "Alpha Carinae",
    spectralClass: "A",
    subtype: "Yellow-white supergiant",
    temperature: 7350,
    massSolar: 8.8,
    radiusSolar: 71,
    luminositySolar: 10700,
    distanceLightYears: 310,
    isAlive: true,
    transmissionAgeYears: 310,
    deathYear: null,
    constellation: "Carina",
    nasaId: "canopus",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Canopus — the second brightest star in the sky, invisible from most of Europe and North America. NASA spacecraft use it as a navigation reference point. This signal left when Louis XIV was on the throne of France.",
    sonificationParams: { baseFrequency: 528, timbre: "sine", pulseRate: null, harmonics: [1, 2, 3, 4] },
  },
  {
    name: "Altair",
    commonName: "Alpha Aquilae",
    spectralClass: "A",
    subtype: "Main sequence",
    temperature: 7670,
    massSolar: 1.79,
    radiusSolar: 1.63,
    luminositySolar: 10.6,
    distanceLightYears: 16.7,
    isAlive: true,
    transmissionAgeYears: 16.7,
    deathYear: null,
    constellation: "Aquila",
    nasaId: "altair",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Altair rotates so fast — once every 9 hours — that it bulges at the equator and is noticeably flattened. This has been directly observed. The signal arriving now left when the iPhone had just been invented.",
    sonificationParams: { baseFrequency: 528, timbre: "sine", pulseRate: null, harmonics: [1, 2, 3] },
  },
  {
    name: "Beta Pictoris",
    commonName: null,
    spectralClass: "A",
    subtype: "Main sequence",
    temperature: 8052,
    massSolar: 1.75,
    radiusSolar: 1.5,
    luminositySolar: 8.7,
    distanceLightYears: 63,
    isAlive: true,
    transmissionAgeYears: 63,
    deathYear: null,
    constellation: "Pictor",
    nasaId: "beta_pictoris",
    imageUrl: null,
    generatedImageUrl: null,
    description: "Beta Pictoris is surrounded by one of the most studied protoplanetary disks in the sky. Multiple planets orbit within the disk. The signal arriving now left in 1962 — the year of the Cuban Missile Crisis.",
    sonificationParams: { baseFrequency: 528, timbre: "sine", pulseRate: null, harmonics: [1, 2, 3] },
  },
  {
    name: "WR 104",
    commonName: null,
    spectralClass: "O",
    subtype: "Wolf-Rayet binary",
    temperature: 45000,
    massSolar: 25,
    radiusSolar: 5,
    luminositySolar: 630000,
    distanceLightYears: 8000,
    isAlive: true,
    transmissionAgeYears: 8000,
    deathYear: null,
    constellation: "Sagittarius",
    nasaId: "wr104",
    imageUrl: null,
    generatedImageUrl: null,
    description: "WR 104 is a pinwheel nebula — two massive stars spiraling together, trailing a 200-billion-kilometer coil of gas. A Wolf-Rayet binary candidate for a hypernova. One axis points toward Earth. Its gamma-ray burst, if it occurs, would be significant. The signal left 6,000 years before the pyramids were built.",
    sonificationParams: { baseFrequency: 880, timbre: "sawtooth", pulseRate: 18.5, harmonics: [1, 2, 3, 4, 5] },
  },
  // DEAD STARS
  {
    name: "Sanduleak -69° 202",
    commonName: "SN 1987A progenitor",
    spectralClass: "B",
    subtype: "Blue supergiant (deceased)",
    temperature: 16000,
    massSolar: 20,
    radiusSolar: 40,
    luminositySolar: 100000,
    distanceLightYears: 168000,
    isAlive: false,
    transmissionAgeYears: 168000,
    deathYear: -166013, // died 168,000 years ago, supernova observed 1987
    constellation: "Dorado",
    nasaId: "sn1987a",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/SN1987A_HST.jpg/800px-SN1987A_HST.jpg",
    generatedImageUrl: null,
    description: "This star died 168,000 years ago in the Large Magellanic Cloud. On February 23, 1987, humanity witnessed its death — supernova SN 1987A, the closest observed supernova in nearly 400 years. Neutrinos from the explosion arrived three hours before light, traveling through solid rock as if it were air. What you hear is a ghost.",
    sonificationParams: { baseFrequency: 660, timbre: "sawtooth", pulseRate: null, harmonics: [1, 2, 3, 4, 5] },
  },
  {
    name: "Tycho's Star",
    commonName: "SN 1572",
    spectralClass: "B",
    subtype: "Type Ia supernova remnant (deceased)",
    temperature: 10000,
    massSolar: 1.4,
    radiusSolar: 1,
    luminositySolar: 50000,
    distanceLightYears: 8000,
    isAlive: false,
    transmissionAgeYears: 8000,
    deathYear: 1572,
    constellation: "Cassiopeia",
    nasaId: "sn1572",
    imageUrl: null,
    generatedImageUrl: null,
    description: "In November 1572, a new star appeared — brighter than Venus, visible in daylight. Tycho Brahe observed it carefully, disproving the Aristotelian belief that the heavens were unchanging. The star died before any European had seen the New World. What you hear is 452 years old — from a star that no longer exists.",
    sonificationParams: { baseFrequency: 660, timbre: "sawtooth", pulseRate: null, harmonics: [1, 2, 3, 4] },
  },
  {
    name: "Kepler's Star",
    commonName: "SN 1604",
    spectralClass: "O",
    subtype: "Type Ia supernova remnant (deceased)",
    temperature: 30000,
    massSolar: 1.4,
    radiusSolar: 1,
    luminositySolar: 80000,
    distanceLightYears: 20000,
    isAlive: false,
    transmissionAgeYears: 20000,
    deathYear: 1604,
    constellation: "Ophiuchus",
    nasaId: "sn1604",
    imageUrl: null,
    generatedImageUrl: null,
    description: "The last naked-eye supernova observed in our galaxy. Johannes Kepler studied it for over a year. Galileo used it to argue against Aristotle. For three weeks it outshone every star in the sky. It died 20,000 years ago — its light arriving in the year Shakespeare was writing Othello.",
    sonificationParams: { baseFrequency: 880, timbre: "sawtooth", pulseRate: null, harmonics: [1, 2, 3, 4, 5] },
  },
  {
    name: "V838 Monocerotis",
    commonName: null,
    spectralClass: "K",
    subtype: "Luminous red nova",
    temperature: 3270,
    massSolar: 5,
    radiusSolar: 380,
    luminositySolar: 600000,
    distanceLightYears: 20000,
    isAlive: true,
    transmissionAgeYears: 20000,
    deathYear: null,
    constellation: "Monoceros",
    nasaId: "v838_mon",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/V838_Monocerotis_expanding_light_echo.jpg/800px-V838_Monocerotis_expanding_light_echo.jpg",
    generatedImageUrl: null,
    description: "In 2002, V838 Monocerotis briefly became one of the most luminous stars in the galaxy. The Hubble Space Telescope captured its expanding light echo — shells of ancient dust illuminated like a time-lapse of the explosion. What caused it remains unknown. The signal arriving now left 20,000 years ago.",
    sonificationParams: { baseFrequency: 261, timbre: "triangle", pulseRate: 7.3, harmonics: [1, 1.5, 2] },
  },
];

function generateLightCurve(
  spectralClass: string,
  pulseRate: number | null,
  n = 300
): Array<{ time: number; flux: number }> {
  const variability: Record<string, number> = {
    O: 0.05, B: 0.03, A: 0.02, F: 0.08, G: 0.01, K: 0.015, M: 0.04,
  };
  const cls = spectralClass?.charAt(0).toUpperCase() || "G";
  const noise = variability[cls] || 0.02;
  const period = pulseRate ? (60 / pulseRate) * 24 : 0;

  return Array.from({ length: n }, (_, i) => {
    const t = (i / n) * 100;
    let flux = 1.0;
    if (period > 0) {
      flux += Math.sin((2 * Math.PI * t) / period) * noise * 3;
    }
    flux += (Math.random() - 0.5) * noise * 2;
    if (Math.random() < 0.005) flux -= noise * 8 * Math.random();
    return { time: t, flux: Math.max(0.8, Math.min(1.2, flux)) };
  });
}

async function seed() {
  console.log("Seeding stars...");

  // Clear existing data
  await db.delete(lightCurvePointsTable);
  await db.delete(starsTable);

  for (const star of STARS) {
    const [inserted] = await db.insert(starsTable).values(star).returning();
    console.log(`  Inserted: ${inserted.name} (id=${inserted.id})`);

    // Generate and insert light curve
    const points = generateLightCurve(
      star.spectralClass,
      star.sonificationParams.pulseRate
    );
    await db.insert(lightCurvePointsTable).values(
      points.map(p => ({ starId: inserted.id, time: p.time, flux: p.flux }))
    );
  }

  console.log(`Done. Seeded ${STARS.length} stars.`);
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
